import { useEffect,useMemo,useState } from "react";
import type { Category,ServerStatus,Torrent } from "@harbor/contracts";
import { AlertTriangle,Anchor,CheckCircle2,Download,FolderCheck,History,LayoutGrid,MoreHorizontal,Pause,Play,Plus,Search,Settings,SlidersHorizontal,Upload,Wifi,X } from "lucide-react";
import { api,connection } from "./lib/api";
import { Pairing } from "./components/Pairing";
import { AddTorrent } from "./components/AddTorrent";
import { PlanTimer } from "./components/PlanTimer";

const fmtSpeed=(n:number)=>n?`${(n/1e6).toFixed(1)} MB/s`:'—';const fmtSize=(n:number)=>n<0?'—':`${(n/1e9).toFixed(1)} GB`;const fmtEta=(n:number|null)=>n===null?'Waiting':n===0?'Done':`${Math.floor(n/60)}m ${n%60}s`;

export function App(){
  const[paired,setPaired]=useState(!!connection.get()),[items,setItems]=useState<Torrent[]>([]),[status,setStatus]=useState<ServerStatus|null>(null),[adding,setAdding]=useState(false),[reviewing,setReviewing]=useState<Torrent|null>(null),[query,setQuery]=useState(""),[filter,setFilter]=useState("all"),[error,setError]=useState("");
  async function refresh(){try{const[t,s]=await Promise.all([api.list(),api.status()]);setItems(t);setStatus(s);setError(s.engineConnected===false?s.engineError||"qBittorrent is disconnected":s.storageReady===false?`Storage needs attention: ${s.storageIssues?.join(", ")}`:"")}catch(e){setError(e instanceof Error?e.message:"Disconnected")}}
  useEffect(()=>{if(!paired)return;refresh();const id=setInterval(refresh,1200);return()=>clearInterval(id)},[paired]);
  const visible=useMemo(()=>items.filter(t=>(filter==="all"||filter==="active"&&["queued","downloading"].includes(t.status)||filter==="review"&&t.status==="review"||filter==="complete"&&["organized","completed"].includes(t.status))&&t.name.toLowerCase().includes(query.toLowerCase())),[items,filter,query]);
  if(!paired)return <><Pairing onPaired={()=>setPaired(true)}/><PlanTimer completed={2}/></>;
  return <div className="app-shell"><aside className="sidebar"><div className="brand"><span className="logo"><Anchor/></span><strong>Harbor</strong></div><nav><Nav icon={<LayoutGrid/>} label="Downloads" active count={items.filter(x=>x.status==="downloading").length}/><Nav icon={<AlertTriangle/>} label="Needs review" count={items.filter(x=>x.status==="review").length}/><Nav icon={<History/>} label="History"/><Nav icon={<FolderCheck/>} label="Library"/><div className="nav-rule"/><Nav icon={<Settings/>} label="Settings"/></nav><div className="server-card"><div><span className={error?"status-dot offline":"status-dot"}/><strong>{connection.get()?.serverName}</strong></div><small>{error?"Connection interrupted":`${status?.engine??"…"} engine · Online`}</small><div className="server-stats"><span><Download/> {fmtSpeed(status?.downloadSpeed??0)}</span><span><Upload/> {fmtSpeed(status?.uploadSpeed??0)}</span></div></div></aside><main className="content"><header className="topbar"><div><p className="eyebrow">YOUR SERVER</p><h1>Downloads</h1></div><div className="top-actions"><button className="connection"><Wifi/> {error?"Attention needed":"Unraid connected"}</button><button className="primary" onClick={()=>setAdding(true)}><Plus/> Add torrent</button></div></header><section className="summary"><div><small>ACTIVE</small><strong>{items.filter(x=>x.status==="downloading").length}</strong><span>transfers</span></div><div><small>DOWNLOADING</small><strong>{fmtSpeed(status?.downloadSpeed??0)}</strong><Download/></div><div><small>UPLOADING</small><strong>{fmtSpeed(status?.uploadSpeed??0)}</strong><Upload/></div><div><small>NEEDS REVIEW</small><strong>{items.filter(x=>x.status==="review").length}</strong><AlertTriangle/></div></section><section className="toolbar"><div className="tabs">{[["all","All"],["active","Active"],["complete","Completed"],["review","Needs review"]].map(([id,label])=><button className={filter===id?"active":""} onClick={()=>setFilter(id!)} key={id}>{label}</button>)}</div><div className="tools"><label className="search"><Search/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search downloads"/></label><button className="icon-button"><SlidersHorizontal/></button></div></section>{error&&<div className="offline-banner"><AlertTriangle/> {error}. Harbor will reconnect automatically.</div>}<section className="torrent-list"><div className="list-head"><span>NAME</span><span>SIZE</span><span>PROGRESS</span><span>SPEED</span><span>ETA</span><span/></div>{visible.length?visible.map(t=><TorrentRow key={t.id} torrent={t} refresh={refresh} review={()=>setReviewing(t)}/>):<Empty add={()=>setAdding(true)} filtered={!!query||filter!=="all"}/>}</section></main>{adding&&<AddTorrent close={()=>setAdding(false)} added={refresh}/>} {reviewing&&<Review torrent={reviewing} close={()=>setReviewing(null)} saved={()=>{setReviewing(null);refresh()}}/>}<PlanTimer completed={3}/></div>
}

function Nav({icon,label,active,count}:{icon:React.ReactNode;label:string;active?:boolean;count?:number}){return <button className={active?"nav-item active":"nav-item"}>{icon}<span>{label}</span>{!!count&&<b>{count}</b>}</button>}
function TorrentRow({torrent:t,refresh,review}:{torrent:Torrent;refresh:()=>void;review:()=>void}){const[actionOpen,setActionOpen]=useState(false),[expanded,setExpanded]=useState(false);async function act(action:string){setActionOpen(false);await api.action(t.id,action);refresh()}return <><article className="torrent-row"><div className="torrent-name" onClick={()=>setExpanded(!expanded)}><div className={`file-icon ${t.classification.category}`}><Download/></div><div><strong>{t.name}</strong><p><span className="category">{t.classification.category}</span><span>to {t.destination}</span><span>{t.seeds} seeds · {t.peers} peers</span></p></div></div><span>{fmtSize(t.size)}</span><div className="progress"><div><i style={{width:`${Math.round(t.progress*100)}%`}}/></div><p><b>{Math.round(t.progress*100)}%</b><span>{fmtSize(t.downloaded)} of {fmtSize(t.size)}</span></p></div><div className="speed"><strong>{fmtSpeed(t.downloadSpeed)}</strong><small>↑ {fmtSpeed(t.uploadSpeed)}</small></div><span className="eta">{t.status==="review"?<button className="review-link" onClick={review}>Review</button>:t.status==="organized"?<em className="complete"><CheckCircle2/> Organized</em>:fmtEta(t.etaSeconds)}</span><div className="row-actions"><button className="icon-button" title={t.status==="paused"?"Resume":"Pause"} onClick={()=>act(t.status==="paused"?"resume":"pause")}>{t.status==="paused"?<Play/>:<Pause/>}</button><button className="icon-button" onClick={()=>setActionOpen(!actionOpen)}><MoreHorizontal/></button>{actionOpen&&<div className="action-menu"><button onClick={()=>act("recheck")}>Recheck files</button><button className="danger" onClick={async()=>{if(confirm("Remove this torrent from Harbor? Downloaded data will be kept.")){await api.remove(t.id);refresh()}}}>Remove torrent</button></div>}</div></article>{expanded&&<div className="file-details"><header><strong>Files</strong><span>{t.files.length} items</span></header>{t.files.map(file=><div key={file.id}><span>{file.name}</span><span>{fmtSize(file.size)}</span><select value={file.priority} onChange={async e=>{await api.filePriority(t.id,[file.id],Number(e.target.value));refresh()}}><option value="0">Skip</option><option value="1">Normal</option><option value="6">High</option><option value="7">Maximum</option></select></div>)}</div>}</>}
function Review({torrent,close,saved}:{torrent:Torrent;close:()=>void;saved:()=>void}){const[category,setCategory]=useState(torrent.classification.category),[title,setTitle]=useState(torrent.classification.title),[season,setSeason]=useState(torrent.classification.season?.toString()??""),[episode,setEpisode]=useState(torrent.classification.episode?.toString()??""),[error,setError]=useState("");async function save(){try{await api.correct(torrent.id,{category,title,season:season?Number(season):undefined,episode:episode?Number(episode):undefined});saved()}catch(e){setError(e instanceof Error?e.message:"Correction failed")}}return <div className="scrim"><section className="sheet review-sheet"><header><div><p className="eyebrow">NEEDS REVIEW</p><h2>Choose where this belongs</h2></div><button className="icon-button" onClick={close}><X/></button></header><p className="lede">Harbor was only {Math.round(torrent.classification.confidence*100)}% confident because {torrent.classification.reasons.join(", ")}. Nothing will be organized until you confirm.</p><div className="field-grid"><label>Category<select value={category} onChange={e=>setCategory(e.target.value as Exclude<Category,"auto">)}>{["movie","tv","game","music","software","book","general","review"].map(x=><option value={x} key={x}>{x}</option>)}</select></label><label>Title<input value={title} onChange={e=>setTitle(e.target.value)}/></label>{category==="tv"&&<><label>Season<input type="number" min="0" value={season} onChange={e=>setSeason(e.target.value)}/></label><label>Episode (blank for pack)<input type="number" min="0" value={episode} onChange={e=>setEpisode(e.target.value)}/></label></>}</div><div className="safe-note"><FolderCheck/><span>Destination: <strong>{torrent.destination}</strong>. The corrected category mapping is applied when you confirm.</span></div>{error&&<div className="error">{error}</div>}<footer><button className="quiet" onClick={close}>Leave in review</button><button className="primary" onClick={save}>Confirm and organize</button></footer></section></div>}
function Empty({add,filtered}:{add:()=>void;filtered:boolean}){return <div className="empty"><div className="empty-rings"><Anchor/></div><h2>{filtered?"Nothing matches":"Your harbor is calm"}</h2><p>{filtered?"Try changing the search or filter.":"Send a torrent to Unraid and it will appear here with live progress."}</p>{!filtered&&<button className="primary" onClick={add}><Plus/> Add your first torrent</button>}</div>}
